// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesSystem.Api.Persistence;

#nullable disable

namespace SalesSystem.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601072221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUSTOMER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_CUSTOMERS");

                    b.HasIndex("CustomerCode")
                        .IsUnique()
                        .HasDatabaseName("UX_CUSTOMERS_CUSTOMER_CODE");

                    b.ToTable("CUSTOMERS", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.CustomerVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALID_FROM");

                    b.HasKey("Id")
                        .HasName("PK_CUSTOMER_VERSIONS");

                    b.HasAlternateKey("Id", "CustomerId")
                        .HasName("AK_CUSTOMER_VERSIONS_ID_CUSTOMER_ID");

                    b.HasIndex("CustomerId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_CUSTOMER_VERSIONS_CUSTOMER_ID_VALID_FROM");

                    b.ToTable("CUSTOMER_VERSIONS", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("PRODUCT_CODE");

                    b.HasKey("Id")
                        .HasName("PK_PRODUCTS");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasDatabaseName("UX_PRODUCTS_PRODUCT_CODE");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.ProductVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_DISCONTINUED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<decimal>("StandardUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("STANDARD_UNIT_PRICE");

                    b.Property<string>("TaxCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("TAX_CATEGORY");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("UNIT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALID_FROM");

                    b.HasKey("Id")
                        .HasName("PK_PRODUCT_VERSIONS");

                    b.HasAlternateKey("Id", "ProductId")
                        .HasName("AK_PRODUCT_VERSIONS_ID_PRODUCT_ID");

                    b.HasIndex("ProductId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_PRODUCT_VERSIONS_PRODUCT_ID_VALID_FROM");

                    b.ToTable("PRODUCT_VERSIONS", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<long>("CustomerVersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_VERSION_ID");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("SALES_DATE");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.HasKey("Id")
                        .HasName("PK_SALES");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_SALES_CUSTOMER_ID");

                    b.HasIndex("CustomerVersionId")
                        .HasDatabaseName("IX_SALES_CUSTOMER_VERSION_ID");

                    b.HasIndex("SalesDate")
                        .HasDatabaseName("IX_SALES_SALES_DATE");

                    b.HasIndex("CustomerVersionId", "CustomerId");

                    b.ToTable("SALES", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.SaleDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("AMOUNT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<long>("ProductVersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_VERSION_ID");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("QUANTITY");

                    b.Property<long>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SALE_ID");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TAX_AMOUNT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("TAX_RATE");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("Id")
                        .HasName("PK_SALE_DETAILS");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SALE_DETAILS_PRODUCT_ID");

                    b.HasIndex("ProductVersionId")
                        .HasDatabaseName("IX_SALE_DETAILS_PRODUCT_VERSION_ID");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("IX_SALE_DETAILS_SALE_ID");

                    b.HasIndex("ProductVersionId", "ProductId");

                    b.ToTable("SALE_DETAILS", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.TaxRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("RATE");

                    b.Property<string>("TaxCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("TAX_CATEGORY");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALID_FROM");

                    b.HasKey("Id")
                        .HasName("PK_TAX_RATES");

                    b.HasIndex("TaxCategory", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_TAX_RATES_TAX_CATEGORY_VALID_FROM");

                    b.ToTable("TAX_RATES", (string)null);
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.CustomerVersion", b =>
                {
                    b.HasOne("SalesSystem.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("Versions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CUSTOMER_VERSIONS_CUSTOMERS");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.ProductVersion", b =>
                {
                    b.HasOne("SalesSystem.Api.Domain.Entities.Product", "Product")
                        .WithMany("Versions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCT_VERSIONS_PRODUCTS");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Sale", b =>
                {
                    b.HasOne("SalesSystem.Api.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALES_CUSTOMERS");

                    b.HasOne("SalesSystem.Api.Domain.Entities.CustomerVersion", "CustomerVersion")
                        .WithMany()
                        .HasForeignKey("CustomerVersionId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALES_CUSTOMER_VERSIONS");

                    b.Navigation("Customer");

                    b.Navigation("CustomerVersion");
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.SaleDetail", b =>
                {
                    b.HasOne("SalesSystem.Api.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALE_DETAILS_PRODUCTS");

                    b.HasOne("SalesSystem.Api.Domain.Entities.Sale", "Sale")
                        .WithMany("Details")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALE_DETAILS_SALES");

                    b.HasOne("SalesSystem.Api.Domain.Entities.ProductVersion", "ProductVersion")
                        .WithMany()
                        .HasForeignKey("ProductVersionId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALE_DETAILS_PRODUCT_VERSIONS");

                    b.Navigation("Product");

                    b.Navigation("ProductVersion");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Product", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SalesSystem.Api.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
